<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ZSCHN01LP0391" failures="1" tests="6" name="runners.MyTestRunner" time="11.406" errors="0" timestamp="2024-02-19T15:02:53 IST" skipped="0">
  <testcase classname="runners.MyTestRunner" name="runScenario" time="1.324"/>
  <system-out/>
  <testcase classname="runners.MyTestRunner" name="runScenario" time="1.429"/>
  <system-out/>
  <testcase classname="runners.MyTestRunner" name="runScenario" time="4.873"/>
  <system-out/>
  <testcase classname="runners.MyTestRunner" name="runScenario" time="1.405">
    <failure message="expected [Amazon S] but found [Amazon S3]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Amazon S] but found [Amazon S3]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefs.ArticleStepDefinition.should_display_the_new_article_title(ArticleStepDefinition.java:215)
at âœ½.Should display the new Article Title(file:///C:/Workspace/FinalCaseStudy/src/test/resources/features/ArticleManagement.feature:53)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runners.MyTestRunner" name="runScenario" time="0.793"/>
  <system-out/>
  <testcase classname="runners.MyTestRunner" name="runScenario" time="1.582"/>
  <system-out/>
</testsuite> <!-- runners.MyTestRunner -->
